# -*- coding: utf-8 -*-
"""Python20230205.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rozhSR124E3y1MxtioCRdGMuNKq-OApD

Python 2023/2/5

練習
bin(binary)二進位
oct(octal)八進位
hex(hexadecimal)十六進位
"""

a = int(input())
b = a + 1
print(b)

b = int(0.9999999)
int(b)

a = 344
print(bin(a))
print(oct(a))
print(hex(a))

swap()
def swap():
    a,b = b,a
    print(a,b)

